import GlobalState from '@/context'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Zando',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`bg-slate-950 inter.className`}>
        <GlobalState>
          <Navbar/>
          <main className='flex min-h-screen flex-col mt-[80px] bg-blue-950'>{children}</main>
        </GlobalState>
      </body>
    </html>
  )
}
